version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: test-order
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-database
    ports:
      - 15434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: