services:
  storageservice.api:
    image: storageservice.api
    build:
      context: ..
      dockerfile: StorageService/StorageService.Api/Dockerfile
    ports:
      - "8080:5228"
      - "8081:5229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=storagedb;Username=storageuser;Password=storagepass
    depends_on:
      db:
        condition: service_healthy
    networks:
      - storagenetwork

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=storagedb
      - POSTGRES_USER=storageuser
      - POSTGRES_PASSWORD=storagepass
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storageuser -d storagedb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - storagenetwork

networks:
  storagenetwork:
    driver: bridge

volumes:
  postgres_data: