<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Core.Common\Core.Common.csproj" />
        <ProjectReference Include="..\OzonMarket.Application\OzonMarket.Application.csproj" />
        <ProjectReference Include="..\OzonMarket.Domain\OzonMarket.Domain.csproj" />
        <ProjectReference Include="..\OzonMarket.Infrastructure\OzonMarket.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="@(Content)">
            <Visible Condition="'%(NuGetItemType)' == 'Content'">false</Visible>
        </Content>
    </ItemGroup>

</Project>
