<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.10" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OzonMarketOrder.Application\OzonMarketOrder.Application.csproj" />
      <ProjectReference Include="..\OzonMarketOrder.Domain\OzonMarketOrder.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
