name: build and test

on:
  push:
  pull_request:
    branches: ['*']
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build-and-test-product-service:
    name: product-service
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: src/ProductService

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

  build-and-test-storage-service:
    name: storage-service
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: src/StorageService

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

  build-and-test-order-service:
    name: order-service
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: src/OrderService

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal